name: Google Books Tests

on: [push]

jobs:
  cypress-run:
  runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: cypress-io/github-action@v5
      - name: Install dependencies
        run: npm install
      - name: Run component tests
        run: npx cypress run-ct
